- name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.9'

  - name: Install Dependencies
    # Install firebase-admin untuk koneksi database
    run: pip install firebase-admin

  - name: Jalankan Script Pembersih
    # Menggunakan secret yang sama persis dengan script update Anda
    env:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
    run: python cleanup_db.py
